# Generated by Django 6.0 on 2025-12-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DNSRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('record_type', models.CharField(choices=[('A', 'A'), ('AAAA', 'AAAA'), ('CNAME', 'CNAME'), ('MX', 'MX'), ('TXT', 'TXT'), ('PTR', 'PTR'), ('NS', 'NS')], default='A', max_length=10)),
                ('value', models.CharField(max_length=512)),
                ('ttl', models.PositiveIntegerField(default=300)),
                ('priority', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DNS Record',
                'verbose_name_plural': 'DNS Records',
                'indexes': [models.Index(fields=['domain', 'record_type'], name='records_dns_domain_d202d8_idx')],
                'unique_together': {('domain', 'record_type', 'value')},
            },
        ),
    ]
